--Exercitiul 1 - 2 Conectat :)

--Exercitiul 3
desc COUNTRIES;
desc DEPARTMENTS;
desc EMPLOYEES;
desc JOB_GRADES;
desc JOB_HISTORY;
desc JOBS;
desc LOCATIONS;
desc REGIONS;

--Exercitiul 4
SELECT * FROM COUNTRIES;
SELECT * FROM DEPARTMENTS;
SELECT * FROM EMPLOYEES;
SELECT * FROM JOB_GRADES;
SELECT * FROM JOB_HISTORY;
SELECT * FROM JOBS;
SELECT * FROM LOCATIONS;
SELECT * FROM REGIONS;

--Exercitiul 5
RUN;

--EXERCITIUL 6;
desc EMPLOYEES;
RUN;

--EXERCITIUL 7
SELECT EMPLOYEE_ID, LAST_NAME, JOB_ID,HIRE_DATE FROM EMPLOYEES;


--EXERCITIUL 9
SELECT DISTINCT JOB_ID FROM EMPLOYEES;
--EXERCITIUL 10
SELECT LAST_NAME || ', ' ||JOB_ID "Angajat si titlu" FROM EMPLOYEES; 

--EXERCITIUL 11
SELECT LAST_NAME, SALARY FROM EMPLOYEES WHERE SALARY > 2850;

--EXERCITIUL 12
SELECT LAST_NAME, DEPARTMENT_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 104;

--EXERCITIUL 15
SELECT LAST_NAME, JOB_ID, HIRE_DATE FROM EMPLOYEES WHERE HIRE_DATE BETWEEN '20-FEB-1987' AND '1-MAY-1989' ORDER BY HIRE_DATE;

--EXERCITIUL 16
SELECT LAST_NAME, DEPARTMENT_ID FROM EMPLOYEES WHERE DEPARTMENT_ID IN (10, 30) ORDER BY LAST_NAME;

--EXERCITIUL 17
SELECT SYSDATE from dual;

